#cache:
#  paths:
#    - /apt-cache
#    - /go/src/github.com
#    - /go/src/golang.org
#    - /go/src/google.golang.org
#    - /go/src/gopkg.in
#
#stages:
#  - build
#  - test
#  - deploy
#
#before_script:
#  - apk add --no-cache --upgrade bash
#  - echo $CI_PROJECT_DIR
#  - mkdir -p /go/src/git.iu7.bmstu.ru/kaa20u554 /go/src/_/builds
#  - cp -r $CI_PROJECT_DIR /go/src/git.iu7.bmstu.ru/kaa20u554/testing
#  - ln -s /go/src/git.iu7.bmstu.ru/kaa20u554 /go/src/_/builds/kaa20u554
#  - pwd
#  - ls
#  - cd backend
#  - pwd
#  - ls
#  - make build
#
#build-job:
#  stage: build
#  script:
#    - make
#
#test-job:
#  stage: test
#  script:
#    - make test

#unit-test:
#  stage: test
#  image: docker:latest
#  services:
#    - docker:dind
#  before_script:
#    - docker info
#    - ls
#  script:
#    - cd src && docker build -t $DOCKER_IMAGE_NAME -f tests.Dockerfile .

#deploy-job:
#  stage: deploy
#  script:
#    - echo "Stage deploy"

stages:
  - test

unit-tests:
  stage: test
  image: golang:alpine3.18
  before_script:
    - apk add make
  script:
    - cd backend
    - go mod tidy
    - make unit-test

integration-tests:
  stage: test
  image: docker:24.0.2-dind-alpine3.18
#  image: golang:alpine3.18
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
    - golang:1.20-alpine
  before_script:
#    - apk add make
#    - apk add go
#    - export GOPATH=/root/go
#    - export PATH=$PATH:$GOPATH/bin
    - docker compose up --build postgres -d
  script:
    - cd backend
    - go mod tidy
    - make integration-test
#  artifacts:
#    paths:
#      - backend/test.log
#      - backend/report.html
#    expire_in: 30 days

#Integration Test:
#  stage: test
#  needs:
#    - Unit Test
#  image: docker:24.0.2-dind-alpine3.18
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_TLS_CERTDIR: ""
#  services:
#    - docker:dind
#  before_script:
#    - apk add make
#    - apk add go
#    - export GOPATH=/root/go
#    - export PATH=$PATH:$GOPATH/bin
#  script:
#    - cd backend
#    - go mod tidy
#    - make install-test-report
#    - make run-integration-test
#  artifacts:
#    paths:
#      - backend/test.log
#      - backend/report.html
#    expire_in: 30 days

#E2E Test:
#  stage: test
#  needs:
#    - Integration Test
#  image: docker:24.0.2-dind-alpine3.18
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_HOST: tcp://docker:2375
#    DOCKER_TLS_CERTDIR: ""
#  services:
#    - docker:dind
#  before_script:
#    - apk add make
#    - apk add go
#    - export GOPATH=/root/go
#    - export PATH=$PATH:$GOPATH/bin
#  script:
#    - cd backend
#    - go mod tidy
#    - make install-test-report
#    - make run-e2e-test
#  artifacts:
#    paths:
#      - backend/test.log
#      - backend/report.html
#      - backend/traffic.log
#    expire_in: 30 days