global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: api
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'app:9001' ]

  - job_name: node
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']