// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	models "github.com/SweetBloody/bmstu_testing/backend/internal/pkg/models"
	mock "github.com/stretchr/testify/mock"
)

// TrackUsecaseI is an autogenerated mock type for the TrackUsecaseI type
type TrackUsecaseI struct {
	mock.Mock
}

// Create provides a mock function with given fields: track
func (_m *TrackUsecaseI) Create(track *models.Track) (int, error) {
	ret := _m.Called(track)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Track) (int, error)); ok {
		return rf(track)
	}
	if rf, ok := ret.Get(0).(func(*models.Track) int); ok {
		r0 = rf(track)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(*models.Track) error); ok {
		r1 = rf(track)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *TrackUsecaseI) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *TrackUsecaseI) GetAll() ([]*models.Track, error) {
	ret := _m.Called()

	var r0 []*models.Track
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Track, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Track); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Track)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTrackById provides a mock function with given fields: id
func (_m *TrackUsecaseI) GetTrackById(id int) (*models.Track, error) {
	ret := _m.Called(id)

	var r0 *models.Track
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*models.Track, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *models.Track); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Track)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, newTrack
func (_m *TrackUsecaseI) Update(id int, newTrack *models.Track) error {
	ret := _m.Called(id, newTrack)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *models.Track) error); ok {
		r0 = rf(id, newTrack)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTrackUsecaseI creates a new instance of TrackUsecaseI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTrackUsecaseI(t interface {
	mock.TestingT
	Cleanup(func())
}) *TrackUsecaseI {
	mock := &TrackUsecaseI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
